Rh/qrw 71
Strexas/qr_web pull request #19
Opened 2024-03-22 10:01 UTC by RustamHabibovv

All the subtasks are performed here are some notes regarding work:
1.) I did not add any profile button to home page, as I am responsible for home page, so therefore I did not want to interrupt others'work, so for now you have to manually go /profie url to acces profile page
2.) As I just finished backend, htmls implemented are very simple and maybe a little bit messy, they are just standing for to visualize features implemented
3.)Two new database model created Profile and Page Profile has one to one user relationship Page has many to one relationship when new user is created automatically new profile page is created and assigned, which is handled by signals.py.
4.) In profile page you can change password , change profile image, delete profile image, create new page and see pages you already have and delete which you want. When user delete his profile image, default profile image is automatically assigned.
5.) I know that it is not good that when user clicks change password or change image it is directed to form in new url, as I need to implement some js code to html files, I will do it in frontend task, so in final form every change will happen in profile page, forms will appear here.

2024-03-27 09:28 UTC, Strexas requested changes
Remove __pycache__ from PR and make pylint, mypy check succesful

2024-04-13 18:57 UTC, RustamHabibovv commented on qr_web/urls.py
> +    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
no it will not work.

2024-04-14 18:06 UTC, RustamHabibovv commented on qr_web/urls.py
> +Url = typing.Union[URLPattern, URLResolver]
can you elaborate more, I did not get exactly what you mean?

2024-04-14 18:12 UTC, Strexas commented on qr_web/urls.py
> +Url = typing.Union[URLPattern, URLResolver]
`from typing import Union`

2024-04-14 18:13 UTC, Strexas commented on qr_web/urls.py
> +Url = typing.Union[URLPattern, URLResolver]
`Url = Union[URLPattern, URLResolver]`

2024-04-15 07:10 UTC, Strexas approved these changes

2024-04-15 07:11 UTC, merged